name: Sync Release

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: menu
          name: menu
          files: menu/lib.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}